### ISSUE TITLE
Incompatible with metro web

### ISSUE THREAD

**Issue by brianjuhl** [LegendApp/legend-motion#12]
Recently switched to metro web due to migrating to Expo Router and legend-motion no longer works. Reported originally on their repo here: https://github.com/expo/router/issues/650

**Error**
`Unable to resolve "@legendapp/motion"`

**Minimal reproducible example**
//app.json
"web": {
"bundler": "metro",
}

// app.tsx
import { AnimatePresence } from '@legendapp/motion';

**Comment by jmeistrich** [comment]
Thanks for the report! If you happen to know how to fix the transpilation issue, a PR would be much appreciated. Otherwise I'll try to fix this as soon as I can.

**Comment by brianjuhl** [comment]
Hey @jmeistrich! Yeah I'm a little out of my depth on this one as I'm pretty new to metro web. I spent a couple of hours attempting to just that with no luck. Apologies for not being more helpful! For my use case and the deadline I ended up migrating to reanimated, but much prefer legend-motion!

**Comment by jmeistrich** [comment]
I think this should be fixed in version 2.2.1. Let me know if that fixed it?

Many thanks to @marklawlor for tracking the issue down in https://github.com/expo/router/issues/650

**Comment by brianjuhl** [comment]
@jmeistrich Thanks you so much!!
