### ISSUE TITLE
ref not working on Motion.View

### ISSUE THREAD

**Issue by mathias-berg** [LegendApp/legend-motion#3]
I'm trying to measure a component with `onLayout` prop on `Motion.View`, but that function that is passed to that prop is never invoked.
If I use a regular `View` everything works just fine.

❌ `<Motion.View onLayout={e => console.log(e)}...` is not working. 
✅ `<View onLayout={e => console.log(e)}...` is working. 

Using version `2.1.1` and tested on web.

Update: Using ref doesn't work either.

❌ `<Motion.View ref={ref}...` is not working, `ref.current` is `undefined`
✅ `<View ref={ref}...` is working. `ref.current` is returning the element.

**Comment by jmeistrich** [comment]
`onLayout` fixed in 2.1.2.

Not passing ref through was a bit of an oversight. I'll fix that shortly.

**Comment by jmeistrich** [comment]
Fixed ref in 2.1.3.

Let me know if you have any issues with that!

**Comment by mathias-berg** [comment]
Both `ref` and `onLayout` works now!
