### ISSUE TITLE
Re-render when `initial` props changed

### ISSUE THREAD

**Issue by panjiesw** [LegendApp/legend-motion#8]
Hi @jmeistrich,

A question and maybe you have some insight on what I'm trying to do with `@legendapp/motion`.

I realized that `initial` props of `Motion.View` won't cause re-render when updated. This maybe has to do with optimization or something, which is great. But I have a use case where the inital will be updated based on a state. 

Take a `Button` example, where the interaction is animating `backgroundColor` with `whileTap` and/or `whileHover`. I'll put the initial bg color into `initial` prop, and put different color in `whileTap` and `whileHover`. Now the problem is, this button has `disabled` state, where the initial color is different than "enabled" state. Now when the `disabled` state is updated, the `Button` bg color doesn't change!

Do you have any idea on how to achieve this use case? Or is this something that can be put into consideration in `@legendapp/motion`?

**Comment by jmeistrich** [comment]
I think you can use the `animate` prop instead of the `initial` prop. `whileHover` and `whileTap` take precedence so hover and tap will animate to those values and then back to the `animate` value when no longer hovered or tapped. Does that work for your usage?
