### ISSUE TITLE
Animations from @legendapp/motion throwing error after migrating to nativewind (v2) from tailwindcss-react-native (v1)

### ISSUE THREAD

**Issue by ammarfaris** [LegendApp/legend-motion#9]
**Describe the bug**
After migrating to nativewind from taildwindcss-react-native, animations from @legendapp/motion seems to still work but now throwing error: 

> styleq: transform typeof [object Object] is not "string".

**To Reproduce**
1. add @legendapp/motion library and configure nativewind library (https://www.nativewind.dev/quick-starts/expo)
2. add  a basic Motion.View component
3. See error in browser console. 

**Expected behavior**
No error in browser console.

**Screenshots**
![Screenshot 2022-09-01 at 10 09 18 AM](https://user-images.githubusercontent.com/1182205/187817530-1f1718c3-bc11-4f0b-ba15-463446a57a41.png)

**Additional context**
Maybe due to @legendapp/motion library still relying on   "tailwindcss-react-native": "^1.3.1" as peerDependencies

**Comment by jmeistrich** [comment]
Thanks! Yes, it's because of the dependency on the old version. I will try to fix that up this weekend.

**Comment by jmeistrich** [comment]
Updated in the latest 2.2.0. Let me know if that works better for you?

**Comment by ammarfaris** [comment]
> Updated in the latest 2.2.0. Let me know if that works better for you?

Not sure why,  but I still get the error after updating to latest 2.2.0
Appreciate your help.

**Comment by jmeistrich** [comment]
@ammarfaris I was never actually able to reproduce the error, just guessed that was the cause. Are you able to share a repo with the error that I can look at? That would help a lot to help me figure out the problem.

**Comment by ammarfaris** [comment]
I no longer use nativewind for now and i am waiting for nativewind v3 to be released in the future (hopefully) ; then i will try this again. thanks. will close this issue for now.
